name: Simple Test Workflows
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  set-up:
    name: Set up env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        node-version: 'lts/*'

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: set-up

    steps:
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run Test
        run: npx playwright test
